### ISSUE TITLE
Question: Is this package just for interim support until ES2015 modules work ?

### ISSUE THREAD

**Issue by deanrad** [apendua/meteor-amd-manager#8]
Also, have you tried `webpack:webpack` , `rocket:modules`, or `universe:modules` ? I've been experimenting with those, but I'm coming back to this one for its simplicity - I just wanted to inquire about your plans for this project for a blog post I'm writing. Thanks.

**Comment by apendua** [comment]
The answer is "pretty much yes". Though, I must emphasize that when I first created this package no-one even heard about "modules" support coming into Meteor. So anyway, when we have modules on board I think no one will ever need to use this package for controlling source files execution order.

I haven't used the other "module" packages. But I believe they goals are slightly different, and surely they go far beyond solving the problem of file ordering, which on the other hand is the main purpose of `amd:manager`. This is may be the reason it feels far more simple than the other existing solutions.

**Comment by apendua** [comment]
@deanius Does this answer your question?

**Comment by deanrad** [comment]
Yes, quite well, thanks :)
